WIP: Add support for PlanPro 1.10
simulate-digital-rail/planpro-importer pull request #13
Opened 2024-12-18 10:23 UTC by arneboockmeyer

2024-12-18 12:50 UTC, lpirl commented on example/example.py
putting the two examples/tests in two functions would remove the need for the comments and would avoid variable reuse, but this is just a nit pick

2024-12-18 12:52 UTC, lpirl commented on planpro_importer/planproimporter.py
variable not required, could return respective reader right away, but no objection to current code

2024-12-18 15:22 UTC, lpirl commented
Very good, thank you. There is nothing I veto. Feel free to merge.

2025-01-07 13:07 UTC, lpirl requested changes

2025-01-07 13:54 UTC, arneboockmeyer commented on planpro_importer/planpro110/reader110.py
> +                        if _second_last_node not in [_geo_edge.ID_GEO_Knoten_A.Wert, _geo_edge.ID_GEO_Knoten_B.Wert]:
Yes, I know. This is due to the long PlanPro identifier. I would keep this as is it, iff thats okay for you.

2025-01-07 14:12 UTC, arneboockmeyer commented on planpro_importer/planpro110/reader110.py
> +                maximum_speed = fstr_fahrweg.Fstr_V_Hg.Wert
I would rather keep it this way :)

2025-01-07 14:22 UTC, lpirl approved these changes
wonderful

2025-01-07 14:23 UTC, merged